name: simpeg-agrogeo24
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - pip
  - numpy==1.23.*
  - simpeg==0.20.*
  - discretize==0.10.*
  - pymatsolver==0.2.*
  - matplotlib==3.7.*
  - pooch==1.8.*
  - ipython
  - jupyter
  - jupyterlab
  # Linters
  - nbqa==1.7.1
  - ruff==0.1.13
  - black==23.12.1
